services:
  director-gateway-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex0-controller-development
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  director-gateway-server:
    build:
      context: .
    ports:
      - "6784:1111"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ex0-controller-development
      PORT: 1111
    depends_on:
      - ex0-postgres

volumes:
  postgres-data:
