services:
  director-gateway-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: director-gateway-development
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  director-gateway-server:
    build:
      context: .
    # ports:
    #   - "6784:1111"
    network_mode: host
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:travel-china-spend-nothing@localhost:5432/director-gateway-dev
      PORT: 1111
    depends_on:
      - director-gateway-postgres
    
volumes:
  postgres-data:
