- name: Install Docker
  become: true
  package:
    name:
      - ca-certificates 
      - curl
    state: latest

- name: Add Docker official GPG key
  become: true
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository to Apt sources
  become: true
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt packages
  become: true
  apt: update_cache=yes

- name: Install Docker
  become: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Add user to docker group
  become: true
  shell: |
    usermod -aG docker {{ user }}

