- name: Set the hostname to {{ hostname }}
  become: true
  command: hostnamectl set-hostname "{{ hostname }}"

- name: Set hostname in /etc/hosts
  become: true
  command: sed -i "s/127.0.1.1.*/127.0.1.1\t{{ hostname }}/g" /etc/hosts