- name: Set the hostname to {{ hostname }}
  become: true
  command: hostnamectl set-hostname "{{ hostname }}"

- name: Set hostname in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1.*'
    line: "127.0.1.1\t{{ hostname }}"
    owner: root
    group: root
    mode: '0644'