name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancel in-progress runs on new PR updates
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    # Required for tauri build
    - name: Install Linux Dependencies (Ubuntu)
      # if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install -y build-essential \
                            curl \
                            wget \
                            file \
                            libssl-dev \
                            libgtk-3-dev \
                            libayatana-appindicator3-dev \
                            librsvg2-dev \
                            libsoup2.4-dev
        # Install from Jammy because not available in Ubuntu 22.04
        echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/ubuntu22.list
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-dev
        sudo rm /etc/apt/sources.list.d/ubuntu22.list

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
    
    # TODO: add website to the build process
    - name: Build
      run: bun turbo run build --filter=!@director/website
