# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    # Required for tauri build
    - name: Install Linux Dependencies (Ubuntu)
      # if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install -y build-essential \
                            curl \
                            wget \
                            file \
                            libssl-dev \
                            libgtk-3-dev \
                            libayatana-appindicator3-dev \
                            librsvg2-dev \
                            libsoup2.4-dev
        # Install from Jammy because not available in Ubuntu 22.04
        echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/ubuntu22.list
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-dev
        sudo rm /etc/apt/sources.list.d/ubuntu22.list

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Lint
      run: bun run lint
    - name: Test
      run: bun run test
    
    # TODO: add website to the build process
    - name: Build
      run: bun turbo run build --filter=!@director/website
    # - name: Build
    #   run: bun run build --filter '@director/desktop'