# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf


    - name: Install uv
      uses: astral-sh/setup-uv@v5

    # - uses: oven-sh/setup-bun@v2
    #   with:
    #     bun-version: latest
    # - name: Install dependencies
    #   run: bun install


    # - name: Install Rust stable
    #   uses: dtolnay/rust-toolchain@stable

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    # - name: Lint
    #   run: bun run lint
    # - name: Test
    #   run: bun run test

    - name: Build
      run: bun turbo run build --filter=!@director/website