name: Deploy

on:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed
  #   branches: [multi-tenancy]
  push:
    branches: [ "multi-tenancy" ]

jobs:
  deploy:
    name: Deploy apps/server to Cloud Run
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/__cloudrun-deploy.yml
    with:
      environment: staging
      service_name: app
      image_name: director-app-staging
      working-directory: packages/gateway
      migrations: true
