name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Release
        run: bun run release
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}