name: Test and Lint
on:
  # pull_request:
  #   types: [synchronize, opened, labeled, ready_for_review]
  push:
    branches: [ "bm/backend" ]


env:
  DATABASE_URL: file:./dev.db

jobs:
  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Prepare Prisma
      run: |
        cd apps/backend
        bun run prisma migrate deploy
        bun run prisma generate
    - name: Test
      run: | 
        cd apps/backend
        bun run test src/commands/__tests__/startSSEServer.test.ts